apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.37.0
<<<<<<< HEAD
  name: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
=======
  name: prometheus-operator-strimzi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-strimzi
>>>>>>> 231f19316f069f5b8b61d58f4f26e1545d328c9e
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: jb-kafka-strimzi
