# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: npm
    directory: '/ui'
    schedule:
      interval: daily
    allow:
      - dependency-type: production
    open-pull-requests-limit: 5
    labels:
      - 'prod'
      - 'dependencies'
      - 'javascript'
  - package-ecosystem: npm
    directory: '/ui'
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    target-branch: 'ui'
    allow:
      - dependency-type: development
    labels:
      - 'dev'
      - 'dependencies'
      - 'javascript'
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 3