apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
    name: kafkaadmin
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple