apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: mirror-maker-2-cluster
spec:
  version: 2.4.0
  replicas: 1
  connectCluster: "mirror-maker-connect-cluster"
  clusters:
  - alias: "kafka-on-premise-cluster-source"
    bootstrapServers: my-cluster-kafka-bootstrap-jb-kafka-strimzi.gse-eda-demos-fa9ee67c9ab6a7791435450358e564cc-0001.us-east.containers.appdomain.cloud:443
    tls:
      trustedCertificates:
        - secretName: my-cluster-cluster-ca-cert
          certificate: ca.crt
  - alias: "event-streams-wdc-as-target"
    bootstrapServers: broker-3-qnprtqnp7hnkssdz.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-1-qnprtqnp7hnkssdz.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-0-qnprtqnp7hnkssdz.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-5-qnprtqnp7hnkssdz.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-2-qnprtqnp7hnkssdz.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-4-qnprtqnp7hnkssdz.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093
    authentication:
      username: token
      passwordSecret:
        secretName: es-apikey-target
        password: password 
      type: plain
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
  mirrors:
  - sourceCluster: "kafka-on-premise-cluster-source"
    targetCluster: "event-streams-wdc-as-target"
    sourceConnector:
      config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
          sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
          heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
          checkpoints.topic.replication.factor: 1
    topicsPattern: "products"
    groupsPattern: ".*"