apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
      app: mm2ocp
    name: mm2ocp
    namespace: jb-kafka-strimzi
spec:
  replicas: 1
  selector:
    app: mm2ocp
  template:
    metadata:
      labels:
        app: mm2ocp
    spec:
      volumes:
      - name: properties-volume
        secret:
          secretName: mm2-std-properties
      containers:
      - image: 'ibmcase/mm2ocp:v0.0.2'
        imagePullPolicy: IfNotPresent
        name: mm2ocp
        volumeMounts:
            - name: properties-volume
              readOnly: true
              mountPath: "/home/kafka-to-es.properties"